# SeedSigner View Classes and their Destinations
# Generated automatically by map_view_destinations.py

VIEW_DESTINATIONS = {
    "AddressVerificationSigTypeView": ["LoadMultisigWalletDescriptorView", "SeedAddressVerificationView", "SeedSelectSeedView"],
    "AddressVerificationStartView": ["AddressVerificationSigTypeView", "LoadMultisigWalletDescriptorView", "SeedAddressVerificationView", "SeedSelectSeedView"],
    "BIP-39 passphrase": ["SettingsEntryUpdateSelectionView"],
    "BIP-85 child seeds": ["SettingsEntryUpdateSelectionView"],
    "Bitcoin network": ["SettingsEntryUpdateSelectionView"],
    "Camera rotation": ["SettingsEntryUpdateSelectionView"],
    "Compact SeedQR": ["SettingsEntryUpdateSelectionView"],
    "Coordinator software": ["SettingsEntryUpdateSelectionView"],
    "Denomination display": ["SettingsEntryUpdateSelectionView"],
    "Display type": ["SettingsEntryUpdateSelectionView"],
    "DonateView": ["SettingsMenuView"],
    "Electrum seeds": ["SettingsEntryUpdateSelectionView"],
    "ErrorView": ["MainMenuView"],
    "IOTestView": ["SettingsMenuView"],
    "Invert colors": ["SettingsEntryUpdateSelectionView"],
    "Language": ["LocaleSelectionView"],
    "LoadMultisigWalletDescriptorView": ["MainMenuView", "ScanWalletDescriptorView"],
    "LoadSeedView": ["ScanSeedQRView", "SeedElectrumMnemonicStartView", "SeedMnemonicEntryView", "ToolsMenuView"],
    "LocaleSelectionView": ["SettingsMenuView"],
    "MainMenuView": ["PowerOptionsView", "ScanView", "SeedsMenuView", "SettingsMenuView", "ToolsMenuView"],
    "Message signing": ["SettingsEntryUpdateSelectionView"],
    "Mnemonic language": ["SettingsEntryUpdateSelectionView"],
    "MultisigWalletDescriptorView": ["MainMenuView", "PSBTChangeDetailsView", "SeedAddressVerificationView", "ToolsAddressExplorerAddressTypeView"],
    "NotYetImplementedView": ["MainMenuView"],
    "OpeningSplashView": [],
    "OptionDisabledView": ["MainMenuView", "SettingsEntryUpdateSelectionView"],
    "PSBTAddressDetailsView": ["PSBTAddressDetailsView", "PSBTChangeDetailsView", "PSBTFinalizeView", "PSBTOpReturnView"],
    "PSBTAddressVerificationFailedView": ["MainMenuView"],
    "PSBTChangeDetailsView": ["LoadMultisigWalletDescriptorView", "MainMenuView", "NotYetImplementedView", "PSBTAddressVerificationFailedView", "PSBTChangeDetailsView", "PSBTFinalizeView", "PSBTOpReturnView"],
    "PSBTFinalizeView": ["MainMenuView", "PSBTSignedQRDisplayView", "PSBTSigningErrorView"],
    "PSBTMathView": ["MainMenuView", "PSBTAddressDetailsView", "PSBTChangeDetailsView"],
    "PSBTNoChangeWarningView": ["PSBTMathView"],
    "PSBTOpReturnView": ["PSBTFinalizeView"],
    "PSBTOverviewView": ["PSBTMathView", "PSBTNoChangeWarningView", "PSBTUnsupportedScriptTypeWarningView"],
    "PSBTSelectSeedView": ["PSBTOverviewView", "ScanSeedQRView", "SeedElectrumMnemonicStartView", "SeedMnemonicEntryView"],
    "PSBTSignedQRDisplayView": ["MainMenuView"],
    "PSBTSigningErrorView": ["MainMenuView", "PSBTSelectSeedView"],
    "PSBTUnsupportedScriptTypeWarningView": ["PSBTAddressDetailsView"],
    "Persistent settings": ["SettingsEntryUpdateSelectionView"],
    "PowerOffView": [],
    "PowerOptionsView": ["PowerOffView", "RestartView"],
    "QR background color": ["SettingsEntryUpdateSelectionView"],
    "QR code density": ["SettingsEntryUpdateSelectionView"],
    "RestartView": [],
    "ScanInvalidQRTypeView": ["MainMenuView"],
    "ScanView": ["AddressVerificationStartView", "ErrorView", "MainMenuView", "MultisigWalletDescriptorView", "NotYetImplementedView", "PSBTSelectSeedView", "ScanInvalidQRTypeView", "SeedAddPassphraseView", "SeedFinalizeView", "SeedSignMessageStartView", "SettingsIngestSettingsQRView"],
    "Script types": ["SettingsEntryUpdateSelectionView"],
    "SeedAddPassphraseExitDialogView": ["SeedAddPassphraseView", "SeedFinalizeView"],
    "SeedAddPassphraseView": ["SeedAddPassphraseExitDialogView", "SeedFinalizeView", "SeedReviewPassphraseView"],
    "SeedAddressVerificationSuccessView": ["MainMenuView"],
    "SeedAddressVerificationView": ["MainMenuView", "SeedAddressVerificationSuccessView"],
    "SeedBIP85ApplicationModeView": ["SeedBIP85SelectChildIndexView"],
    "SeedBIP85InvalidChildIndexView": ["SeedBIP85SelectChildIndexView"],
    "SeedBIP85SelectChildIndexView": ["SeedBIP85InvalidChildIndexView", "SeedWordsWarningView"],
    "SeedBackupView": ["SeedTranscribeSeedQRFormatView", "SeedWordsWarningView"],
    "SeedDiscardView": ["MainMenuView", "SeedFinalizeView", "SeedOptionsView"],
    "SeedElectrumMnemonicStartView": ["SeedMnemonicEntryView"],
    "SeedExportXpubCoordinatorView": ["SeedExportXpubWarningView"],
    "SeedExportXpubCustomDerivationView": ["SeedExportXpubCoordinatorView", "ToolsAddressExplorerAddressTypeView"],
    "SeedExportXpubDetailsView": ["SeedExportXpubQRDisplayView"],
    "SeedExportXpubQRDisplayView": ["MainMenuView"],
    "SeedExportXpubScriptTypeView": ["SeedExportXpubCoordinatorView", "SeedExportXpubCustomDerivationView", "ToolsAddressExplorerAddressTypeView"],
    "SeedExportXpubSigTypeView": ["SeedExportXpubScriptTypeView"],
    "SeedExportXpubWarningView": ["SeedExportXpubDetailsView"],
    "SeedFinalizeView": ["SeedAddPassphraseView", "SeedOptionsView"],
    "SeedMnemonicEntryView": ["MainMenuView", "SeedFinalizeView", "SeedMnemonicEntryView", "SeedMnemonicInvalidView", "ToolsCalcFinalWordFinalizePromptView", "ToolsCalcFinalWordShowFinalWordView"],
    "SeedMnemonicInvalidView": ["MainMenuView", "SeedMnemonicEntryView"],
    "SeedOptionsView": ["MainMenuView", "PSBTOverviewView", "ScanPSBTView", "ScanView", "SeedAddressVerificationView", "SeedBIP85ApplicationModeView", "SeedBackupView", "SeedDiscardView", "SeedExportXpubScriptTypeView", "SeedExportXpubSigTypeView", "SeedSignMessageConfirmMessageView"],
    "SeedReviewPassphraseView": ["SeedAddPassphraseView", "SeedOptionsView"],
    "SeedSelectSeedView": ["ScanView", "SeedAddressVerificationView", "SeedElectrumMnemonicStartView", "SeedMnemonicEntryView", "SeedSignMessageConfirmMessageView"],
    "SeedSignMessageConfirmAddressView": ["NetworkMismatchErrorView", "SeedSignMessageSignedMessageQRView"],
    "SeedSignMessageConfirmMessageView": ["SeedSignMessageConfirmAddressView", "SeedSignMessageConfirmMessageView"],
    "SeedSignMessageSignedMessageQRView": ["MainMenuView"],
    "SeedSignMessageStartView": ["NetworkMismatchErrorView", "NotYetImplementedView", "OptionDisabledView", "SeedSelectSeedView", "SeedSignMessageConfirmMessageView"],
    "SeedTranscribeSeedQRConfirmInvalidQRView": [],
    "SeedTranscribeSeedQRConfirmQRPromptView": ["SeedOptionsView", "SeedTranscribeSeedQRConfirmScanView"],
    "SeedTranscribeSeedQRConfirmScanView": ["SeedTranscribeSeedQRConfirmInvalidQRView", "SeedTranscribeSeedQRConfirmSuccessView", "SeedTranscribeSeedQRConfirmWrongSeedView"],
    "SeedTranscribeSeedQRConfirmSuccessView": ["SeedOptionsView"],
    "SeedTranscribeSeedQRConfirmWrongSeedView": [],
    "SeedTranscribeSeedQRFormatView": ["SeedTranscribeSeedQRWarningView"],
    "SeedTranscribeSeedQRWarningView": ["SeedTranscribeSeedQRWholeQRView"],
    "SeedTranscribeSeedQRWholeQRView": ["SeedTranscribeSeedQRZoomedInView"],
    "SeedTranscribeSeedQRZoomedInView": ["SeedTranscribeSeedQRConfirmQRPromptView"],
    "SeedWordsBackupTestMistakeView": ["SeedWordsBackupTestView", "SeedWordsView"],
    "SeedWordsBackupTestPromptView": ["SeedFinalizeView", "SeedOptionsView", "SeedWordsBackupTestView"],
    "SeedWordsBackupTestSuccessView": ["SeedFinalizeView", "SeedOptionsView"],
    "SeedWordsBackupTestView": ["SeedWordsBackupTestMistakeView", "SeedWordsBackupTestSuccessView", "SeedWordsBackupTestView"],
    "SeedWordsView": ["SeedWordsBackupTestPromptView", "SeedWordsView"],
    "SeedWordsWarningView": ["SeedWordsView"],
    "SeedsMenuView": ["LoadSeedView", "SeedOptionsView"],
    "SettingsEntryUpdateSelectionView": ["SettingsEntryUpdateSelectionView", "SettingsMenuView"],
    "SettingsIngestSettingsQRView": ["MainMenuView"],
    "SettingsMenuView": ["BIP-39 passphrase", "BIP-85 child seeds", "Bitcoin network", "Camera rotation", "Compact SeedQR", "Coordinator software", "Denomination display", "Display type", "DonateView", "Electrum seeds", "IOTestView", "Invert colors", "Language", "LocaleSelectionView", "MainMenuView", "Message signing", "Mnemonic language", "Persistent settings", "QR background color", "QR code density", "Script types", "SettingsEntryUpdateSelectionView", "SettingsMenuView", "Show QR brightness tips", "Show dire warnings", "Show partner logos", "Show privacy warnings", "Show xpub details", "Sig types", "Xpub export"],
    "Show QR brightness tips": ["SettingsEntryUpdateSelectionView"],
    "Show dire warnings": ["SettingsEntryUpdateSelectionView"],
    "Show partner logos": ["SettingsEntryUpdateSelectionView"],
    "Show privacy warnings": ["SettingsEntryUpdateSelectionView"],
    "Show xpub details": ["SettingsEntryUpdateSelectionView"],
    "Sig types": ["SettingsEntryUpdateSelectionView"],
    "ToolsAddressExplorerAddressListView": ["ToolsAddressExplorerAddressListView", "ToolsAddressExplorerAddressView"],
    "ToolsAddressExplorerAddressTypeView": ["ToolsAddressExplorerAddressListView"],
    "ToolsAddressExplorerAddressView": ["ToolsAddressExplorerAddressListView"],
    "ToolsAddressExplorerSelectSourceView": ["ScanSeedQRView", "ScanWalletDescriptorView", "SeedElectrumMnemonicStartView", "SeedExportXpubScriptTypeView", "SeedMnemonicEntryView"],
    "ToolsCalcFinalWordCoinFlipsView": ["ToolsCalcFinalWordShowFinalWordView"],
    "ToolsCalcFinalWordDoneView": ["SeedDiscardView", "SeedFinalizeView"],
    "ToolsCalcFinalWordFinalizePromptView": ["SeedMnemonicEntryView", "ToolsCalcFinalWordCoinFlipsView", "ToolsCalcFinalWordShowFinalWordView"],
    "ToolsCalcFinalWordNumWordsView": ["SeedMnemonicEntryView"],
    "ToolsCalcFinalWordShowFinalWordView": ["ToolsCalcFinalWordDoneView"],
    "ToolsDiceEntropyEntryView": ["SeedWordsWarningView"],
    "ToolsDiceEntropyMnemonicLengthView": ["ToolsDiceEntropyEntryView"],
    "ToolsImageEntropyFinalImageView": ["ToolsImageEntropyMnemonicLengthView"],
    "ToolsImageEntropyLivePreviewView": ["ToolsImageEntropyFinalImageView"],
    "ToolsImageEntropyMnemonicLengthView": ["SeedWordsWarningView"],
    "ToolsMenuView": ["ScanAddressView", "ToolsAddressExplorerSelectSourceView", "ToolsCalcFinalWordNumWordsView", "ToolsDiceEntropyMnemonicLengthView", "ToolsImageEntropyLivePreviewView"],
    "UnhandledExceptionView": ["MainMenuView"],
    "Xpub export": ["SettingsEntryUpdateSelectionView"],
}
